### ISSUE TITLE
Outcome clustering

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#106]
*Description*
As a user, I would like the system to determine categories of outcomes based on precedent data.

Major work will be conducted on #105. The same approach will then be used for #106.

*Scope of Work*
- [x] Preprocessing decisions from outcomes.
- [x] Extract all outcomes from all obtained precedents.
- [x] Cluster outcomes based on sentence similarity.
- [x] Create a text file for each cluster of outcomes where the similar outcomes are saved, for manual review.

*Story Points*
- 8
*Priority*
- High

*Risk*
- High

*Acceptance Criteria*
- Given an outcome, the system should return the cluster label for it.
- Looking at the label's text file, the written outcomes should be similar to the input outcome.

**Comment by Samuel-Campbell** [comment]
Running Out of Memory
----------------------------------------------------
- Solution: PCA for dimension reduction of matrices

**Comment by arekmano** [comment]
what do the axes represent?

**Comment by arekmano** [comment]
Received verbal confirmation about closing story during meeting. Pinging @naregeff to leave a comment

**Comment by naregeff** [comment]
Signing off, it work!

**Comment by naregeff** [comment]
Signing off, it works!
