### ISSUE TITLE
Determine claim award

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#11]
*Description*
- As a user, I want the system to tell me how much my claim is worth

*Scope of Work*

*Acceptance Criteria*

*Story Points*
- 20

*Priority*
- High

*Risk*
- High

**Comment by arekmano** [comment]
What is the worth of a claim? Is it only the predicted compensation that will be awarded or are there additional considerations?

**Comment by naregeff** [comment]
This user story refers to cases where there is a monetary amount at stake, i.e. damage awards (compensatory or punitive).

**Comment by arekmano** [comment]
split into #79 #87 #85 #86 to keep user story size small
