### ISSUE TITLE
Entity extraction from user answers

### ISSUE THREAD

**Issue by Samuel-Campbell** [Cyberjusticelab/JusticeAI#111]
*Description*
As a user, I would like the system to understand the key entities from  my answer.

This story is highly related to #153
 
*Scope of Work*
- [ ] Create entity extraction for boolean fact types.
- [ ] Create entity extraction for number fact types.
- [ ] Create entity extraction for date fact types.
- [ ] Create entity extraction for time frequency fact types.
- [ ] Create entity extraction for time range fact types.
- [ ] Create entity extraction for money fact types.

*Demo requirement*
1. System ask the user: How much did you pay for rent?
2. User responds with : I paid 500$ last month.
3. System understands that the integer of value 500 is the given answer to the question.

*Acceptance Criteria*
- The user is able to x
- The user sees y
- The user hears z

**Comment by arekmano** [comment]
This story depends on the completion of #105 and #107. After this, we will have a much clearer picture of the required facts types.

A cursory look at our data indicates that it will most probably contain the following:
- boolean (yes/no)
- number ($/number of [days,months,weeks])
- number expressed as a String / English word (two, five, seventy...) 
- time + date
- Open ended (user describes their problems/needs)

**Comment by arekmano** [comment]
completed as part of #251
