### ISSUE TITLE
Choose user type before conversation

### ISSUE THREAD

**Issue by lancelafontaine** [Cyberjusticelab/JusticeAI#112]
*Description*
As a user I would like to indicate my user type on a landing page

*Scope of Work*
- [x] Create landing page mock-up  
- [x] Create landing page with user type selection
- [x] Pass user type to dashboard 
- [x] Remove file download on front-end
- [x] Initial conversation session based on the user type
- [x] Remove question of asking user type
- [x] Remove file download, get file list api logic

*Story Points*
- 5

*Priority*
- Medium

*Risk*
- Low

*Demo requirement*
1. The user should see the landing page 
2. The user should be able to select from either tenant or landlord
3. The system should start a conversation related to the user type

*Acceptance Criteria*
1. The user should see the landing page 
2. The user should be able to select from either tenant or landlord
3. The system should start a conversation related to the user type

***Changes***:

**Comment by dodoels** [comment]
![image](https://user-images.githubusercontent.com/12192439/32157395-8eca7706-bd19-11e7-9cdf-1da8f30cb734.png)
This is my suggested logic flow for this story. The UI will be designed based on this flow. I also considered the extensibility of the design for the account story. The new flow will be based on the above one.
![image](https://user-images.githubusercontent.com/12192439/32157429-d212cd6a-bd19-11e7-812e-e29b149da2af.png)

**Comment by dodoels** [comment]
Landing page design (med-fid)
![image](https://user-images.githubusercontent.com/12192439/32201540-1ceec606-bdae-11e7-9ca9-e6bf1ca09919.png)

**Comment by dodoels** [comment]
We should also remove file download, get file list apis in this story

**Comment by choitwao** [comment]
#

**Comment by Vynny** [comment]
Get file metadata endpoint will remain in order to provide an upload trace. File downloading capabilities were removed.

**Comment by naregeff** [comment]
It works!
