### ISSUE TITLE
Obtain detailed and summary of legal document (Privacy Policy)

### ISSUE THREAD

**Issue by lancelafontaine** [Cyberjusticelab/JusticeAI#114]
*Description*
As a user, I would like the system to show me a detailed Privacy Policy as well as a summary of the Privacy Policy

*Scope of Work*
- [x] Create a Privacy Policy
- [x] Create a Privacy Policy summary

*Story Points*
- None as this is a PO story

**Comment by dodoels** [comment]
[Privacy Policy.docx](https://github.com/Cyberjusticelab/JusticeAI/files/1540991/Privacy.Policy.docx)
updated pp

**Comment by arekmano** [comment]
Privacy policy was provided
