### ISSUE TITLE
Obtain detailed and summary of legal document (EULA)

### ISSUE THREAD

**Issue by lancelafontaine** [Cyberjusticelab/JusticeAI#115]
*Description*
As a user, I would like the system to show me a detailed EULA as well as a summary of the EULA 

*Scope of Work*
- [ ] Create a EULA
- [ ] Create a EULA summary

*Story Points*
- None as this is a PO story

**Comment by arekmano** [comment]
Closing as keeping track of this "PO" story does not benefit the project.
