### ISSUE TITLE
Determine claim precedents

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#13]
--------------------------------------------------
USER STORY SPLIT INTO:
#105 
#106 
#107 
#110 
--------------------------------------------------
*Description*
- As a user, I want to see precedents that exist that are similar to my claim

*Scope of Work*

*Acceptance Criteria*

*Story Points*
- 100

*Priority*
- High

*Risk*
- High

**Comment by arekmano** [comment]
One naive solution would be to create a similarity index based on facts extracted from the current claim. This assumes that we have turned previous claims into facts

**Comment by arekmano** [comment]
Original Comment: "%similarity. Map facts and compare."
