### ISSUE TITLE
Dev Story: RASA Data.json generator script

### ISSUE THREAD

**Issue by ghost** [Cyberjusticelab/JusticeAI#147]
*Description*
As a developer, I would like the system to be able to fully attempt to automate data generation from a text file.

*Scope of Work*
- [ ] Generation of "common examples" 
- [ ] Generation of "synonyms"
- [ ] Automatic generation of entities
- [ ] Automatic generation of intents
- [ ] Generation of "Regex" (possible but restricted)
- [ ] Test that it works

*Story Points*
- [1, 2, 3, 5, 8, 13, 20, 40]

*Priority*
- [Low, Medium, High]

*Risk*
- [Low, Medium, High]

*Demo requirement*
1. The user does x
2. The system does y
n. Rest of a use case of a flow chart

*Acceptance Criteria*
- The user is able to x
- The user sees y
- The user hears z

**Documentation, files, diagrams, etc. relating to this feature:**
Url, books, etc.

***Changes***:
- [Optional]

**Comment by arekmano** [comment]
I don't fully understand the scope of this story. What would the source text file be?
