### ISSUE TITLE
DEV STORY: Create Machine-Readable Representations of Precedents

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#151]
*Description*
As a dev, I would like a vector representation of precedents so it can be used for ML.

*Scope of Work*
- [x] Create a BINARY file representing Facts and Outcomes for each precedent

*Acceptance Criteria*
- Binary file can be used to train desired models

**Comment by arekmano** [comment]
Tentative file layout:

> {
  "precedent": "AZ-511123",
  "facts": [1,0,1,0,1,0,1,0...],
  "outcomes": [0,1,0,0,0,1...],
  "lease_termination": 0
}

**Comment by Samuel-Campbell** [comment]
Depends on part of #153

**Comment by naregeff** [comment]
they managed to explain it to me. good stuff. signed off.
