### ISSUE TITLE
Understand user facts and translate to values

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#153]
*Description*
As a user, I would like the system to understand my input fact's values

*Scope of Work*
- [x] Refine facts obtained by clusters
- [x] Look at a all our clusters and determine their types.
- [x] Store the fact & fact types in the database.

*Story Points*
- 8

*Priority*
- High

*Risk*
- High

*Acceptance Criteria*
1. User enters fact values into the system.
2. System incorporates the fact values into its decision-making algorithm,
3. System returns predictions based on fact values

**Comment by Samuel-Campbell** [comment]
Refine clusters
-----------------------------------------------------
- Some facts appear an overwhelming amount of times in the dataset.
- This results in more subtle facts to be treated as noise.
- To get around this issue, we will perform a second pass only on the noise we detected

Clustering
------------------------------------------------------
- Approximately 8 hours to cluster facts
- Estimated 4-6 trial and error based on approximate calculations to obtain good clusters
- Should take a week once the code is written

**Comment by Samuel-Campbell** [comment]
Slack notifications from python script
----------------------------------------------
- Indicate through slack when a ML process is complete 
- Write the stats / log to the channel
- resource: https://github.com/slackapi/python-slackclient

**Comment by arekmano** [comment]
Fact to precedent manipulation
![img_20171113_210023](https://user-images.githubusercontent.com/8740734/32760324-cae0b194-c8bb-11e7-8d81-97e50ac927fd.jpg)

**Comment by choitwao** [comment]
Mark here, I will update digital version of the manipulation diagram

**Comment by choitwao** [comment]
![image](https://user-images.githubusercontent.com/12192439/32764390-3176bdb0-c8d3-11e7-98c5-91950e2d9a41.png)

Digitalized version of manipulation

**Comment by dodoels** [comment]
![clustering](https://user-images.githubusercontent.com/12192439/32765381-1bebda52-c8d8-11e7-86e0-083683da3de0.png)

**Comment by Samuel-Campbell** [comment]
Refining Preprocessing
--------------------------------------------------------------
The following is used to generate dictionary keys. The odds of two sentences having the same meaning while being entered as different keys is dramatically decreased. 

example: 
"I went to the bank January 2017" and "I went to the bank January 2016"

new output:
"I went to the bank date"

These normalized sentences will also be used to compute the sentence vectors from now on.
- Regex money
- Regex dates
- Remove unecessary white spaces
- Remove punctuation

**Comment by choitwao** [comment]
![lease-terminated-supervised](https://user-images.githubusercontent.com/12192439/32867638-4dc37336-ca3c-11e7-80f9-bdd321700f41.png)

After the team discussion, we will try to run supervised training with existing clusters in order to deliver prediction.

**Comment by dodoels** [comment]
After the team discussion, we will try to run supervised training with existing clusters in order to deliver prediction in short time.


![lease-terminated-supervised](https://user-images.githubusercontent.com/12192439/32867687-94ad9b8c-ca3c-11e7-992a-0cefc8d60340.png)

**Comment by Samuel-Campbell** [comment]
Very nice @choitwao

**Comment by arekmano** [comment]
Story was completed for boolean yes/no values, which is a subset of the initial scope of work
