### ISSUE TITLE
See previously understood facts

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#161]
*Description*
As a user, I would like to see all the facts that the system has understood until now UI-wise to the right of the conversation.

*Scope of Work*
- [x] Create a high fidelity UI mockup, showing how the fact display will work.
- [x] Implement Front-end solution

*Acceptance Criteria*
- System asks a question
- The user enters a response
- System interprets response
- The user's interpreted response is then moved into the understood facts' list

**Comment by arekmano** [comment]
Initial sketch of UI:
![image](https://user-images.githubusercontent.com/8740734/32692054-4dfadcc8-c6df-11e7-8467-f3f4912d5c8a.png)

**Comment by arekmano** [comment]
This is lower priority than #217 and #218

**Comment by Vynny** [comment]
Our backend already persists resolved facts and they can be returned via the /conversation/:id endpoint.
Depending on what is required for the front end, however, we may need to add a short description of the fact and the question asked for display purposes. 

![fact_entities](https://user-images.githubusercontent.com/1418403/34127410-07ff3da6-e40b-11e7-93cd-02be0beed0c7.PNG)

**Comment by Vynny** [comment]
First low fidelity mockup for understood fact list, this would require a human readable title for every fact, as well as a way to associate the question asked and the answer provided to the resolved fact. It would also require fact type sensitive information for each fact. Ie: 
Boolean -> T: The dwelling is habitable, F: The dwelling is not habitable

![lowfid1](https://user-images.githubusercontent.com/1418403/34128711-a247ec92-e40f-11e7-9bb7-502bc9955a7d.png)

**Comment by Vynny** [comment]
Second low fidelity mockup for understood fact list. This would only require a short title for each fact that summarizes it well enough at a glance. It would be presented as an overlay (similar to the history function) which would allow viewing, deletion and revision. The overlay would be triggered by clicking on Zeus' head, because that's where knowledge is stored (as far as our user is concerned).

![lowfid2](https://user-images.githubusercontent.com/1418403/34129666-ed6e5780-e412-11e7-8624-aa75f3987a52.png)

**Comment by arekmano** [comment]
2nd low-fi is a good idea, though we need to somehow highlight that Zeus' logo is clickable. Won't be enough to just state it.

**Comment by Vynny** [comment]
There are several ways we could do that,
- It could bounce around every once in a while, most people associate that with clickable stuff (mac users especially)
- The Zeus icon div could have a png halo effect in the background that grows as questions are answered
- Every time a question is answered and a new fact is given by backend, there could be a momenary glow effect around Zeus' head
- On mouseover, the Zeus icon is raised slightly to indicate interactivity

**Comment by ghost** [comment]
I do agree that the 2nd low-fidelity mock-up is a good idea but I do believe that the product owner specified to Bruce that he wanted the list available here at all times without the clickable Zeus avatar.

**Comment by dodoels** [comment]
No, it was just an idea,  not the final design.

**Comment by ghost** [comment]
Understood.

**Comment by naregeff** [comment]
>the product owner specified to Bruce that he wanted the list available here at all times without the clickable Zeus avatar.

I like the methods suggested by @Vynny to indicate clickability. It might be interesting to declutter the interaction screen. 

A compromise between the two could be to show a fact drawer when the first fact is understood, invite users to close the drawer, and make drawer disappear into avatar. Then with every fact, add to the halo.

**Comment by naregeff** [comment]
does what it says it's supposed to do. can't wait to see #162!
