### ISSUE TITLE
Remove previously understood fact

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#162]
*Description*
As a user, I would like to erase previously understood facts from the conversation's list

This story has a prerequisite of story #161

*Scope of Work*
- [ ] Create high fidelity UI mockup
- [ ] Add new question generation logic to NLP

*Acceptance Criteria*
- User answers fact 1, fact 2, fact 3 questions
- User then presses on the remove button associated with the fact 1 question's answer
- Fact 1 is removed from the conversation
- User gets an updated question, based on the current set of facts.

**Comment by lancelafontaine** [comment]
We should clarify whether or not the ML will need to recompute what facts to ask about next once a fact is deleted by the user. If that's the case, we need to make a corresponding user story for this functionality.

**Comment by mihaiqc** [comment]
ML's job is to produce facts and spit them out to NLP. All it has to do, logic has to be assured by them imo. So I don't really understand what the backend has to do in this. All backend should do is communicate to the frontend what to show, in this specific scenario.

**Comment by arekmano** [comment]
That is not a priority within this story IMO. We should keep it as simple as possible (i.e. ask the question they just removed)

**Comment by Vynny** [comment]
Are we just re-asking the question they removed, or is there a way to tell the ml (now or at some point) that a particular fact has a null value and shouldn't be taken into consideration?

**Comment by arekmano** [comment]
ATM we should just re-ask the same question. We can refine the implementation later on should the need arise.

**Comment by naregeff** [comment]
Functionality demonstrated.
