### ISSUE TITLE
Claim: Retaking the rental

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#186]
*Description*
As a landlord, I would like the system to predict whether or not retaking my rental is justified

*Scope of Work*
- [x] Fix/update regexes
- [x] Create supervised learning algorithm benchmark for evaluating predictions
- [x] Implement supervised learning algorithm that can evaluate whether or not retaking my rental is justified based on facts present in the case .
- [x] Extract using regex, or similar technique whether or not  the rental was retaken in a specific case.
- [x] Integrate with NLP

*Demo requirement*
1. The user selects the facts that are relevant to their case
2. The user sends the facts to the system
3. The system displays "Retaking the rental is justified" or "Retaking the rental is not justified" 

*Acceptance Criteria*
- The user is able perform demo steps
- The F1 score of the supervised learning algorithm is >50%.

**Comment by arekmano** [comment]
Moving this out of iteration, as higher priority user stories have come in

**Comment by naregeff** [comment]
Demo not possible. Need to figure out questions, and integrate to NLP.

**Comment by Vynny** [comment]
Was not integrated with NLP. Need to go over fact specifics with Sam prior to integration.

**Comment by naregeff** [comment]
Works, would need to add some legal rules for more accurate predictions.
