### ISSUE TITLE
Chat Interface

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#2]
*Description*
- As a user, I want a chat interface to interact with the system

*Scope of Work*
- [x] Create UI [3 man hours]
- [x] Implement necessary functions for further integration [3 man hours]
- [x] Configure continuous integration to run tests [3 man hours]

*Acceptance Criteria*
- Users can access the web application through browsers and see the UI.

*Story Points*
- 3

*Priority*
- High

*Risk*
- Low

*Demo requirement*
1. Open web browser
2. Access the web application via localhost
3. Verify that the chat interface has loaded error-free

**Documentation, files, diagrams, etc. relating to this feature:**

See uploaded screenshots in comments.

***Changes***:

No changes to the initial engineering solution.

**Comment by naregeff** [comment]
Interface does what it needs to do, i.e. provides a chat interface for a user.
Can't wait to see it boosted on NLP + with a sick UI. 
Closing issue.

**Comment by lancelafontaine** [comment]
![chatbot-ui-1](https://user-images.githubusercontent.com/1548285/31050503-a66362ea-a619-11e7-929c-a5e1d1c2976b.png)
![chatbot-ui-2](https://user-images.githubusercontent.com/1548285/31050504-aaac9e7a-a619-11e7-8de3-100a2d6f3bbb.png)

**Comment by naregeff** [comment]
Please check UI on safari. It seems unstable. Thank you.

**Comment by arekmano** [comment]
Please open a bug when bugs arise. Old user stories should remain closed unless their functionality was not delivered.

Also screenshots of the issue would help in debugging errors.
