### ISSUE TITLE
Claim information gathering

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#20]
*Description*
As a user, I would like the system to ask me questions to get information about my claim

*Scope of Work*
- [x] Create rough draft of categories and questions to ask the client (12 hours)
- [x] Construct decision tree for our bot (4 hours)
- [x] Research and confirmation with lawyer about specific questions and categories (5-20 hours) (Back and forth interaction)
- [x] Confirm questions bot need to ask the users (5 hours)
- [x] Confirm categories that the user could use the bot for (4 hours)
- [x] Confirm possible questions/responses per categories (25 hours)
- [x] Confirm decision tree for our bot (2 hours)

*Story Points*
- 20

*Priority*
- High

*Risk*
- High

*Demo requirement*
1. The user accesses the website from their machine
2. The bot starts the conversation by asking for the user's name
3. The user inputs their name
4. The bot asks the user whether they're a landlord or a tenant
5. The user inputs whether they're a landlord or a tenant
6. The bot asks the user to describe their dilemma
7. The user describes their dilemma using natural language 
8. The bot correctly identifies the category of dispute the dilemma belongs to by associating the dilemma to various articles of jurisprudence, asking for clarification if the bot cannot process the user's input
9. The bot begins asking questions relevant to the category of the dispute in order to build a claim

*Acceptance Criteria*
- ~~The bot is able to identify the type of aid the user requires~~
- ~~The bot is able to ask questions in reference to my particular subject with my particular issue~~
- The bot is able to gather the user's name, person type (landlord/tenant), and ask about their dilemma
- The bot is able to ask questions relevant to building a claim for the user's dilemma

**Documentation, files, diagrams, etc. relating to this feature:**
https://www.rdl.gouv.qc.ca/
http://legisquebec.gouv.qc.ca/fr/ShowDoc/cs/CCQ-1991
http://legisquebec.gouv.qc.ca/en/showdoc/cs/CCQ-1991
https://www.rdl.gouv.qc.ca/fr/etre-locataire/droits-et-obligations-du-locataire
https://www.rdl.gouv.qc.ca/fr/questions-frequentes
https://www.rdl.gouv.qc.ca/fr/etre-locataire/paiement-du-loyer
http://legisquebec.gouv.qc.ca/fr/ShowDoc/cr/R-8.1,%20r.%205 (in front of regie du logement)
http://ccq.lexum.com/w/ccq/fr#!fragment/CHAPITRE_QUATRIEME_DU_LOUAGE_2528133/KGhhc2g6KGNodW5rxIVhbsSHb3JUZXh0OkNIQVBJVFJFX1FVQcScSUVNxJ5EVV9MT8ShR8SeMjUyODEzMyksbm90ZXNRdWVyeTonJyxzY3JvbGxDxIjEijohbsWGZWFyxIfEvsWAxYLFhMWTxZXEh1PEkHRCxYLEnUxFVkFOQ0UsdGFiOnRvYykp
http://legisquebec.gouv.qc.ca/en/showdoc/cs/CCQ-1991

***Changes***:
-

**Comment by lancelafontaine** [comment]
- [ ] Construct decision tree for our bot (? hours)
- [ ] Research and confirmation with lawyer about specific questions and categories (? hours)
- [ ] Determine questions bot need to ask the users (? hours)
- [ ] Determine categories that the user could use the bot for (? hours)
- [ ] Determine possible questions/responses per categories (? hours)

**Comment by lancelafontaine** [comment]
![20170929_193506](https://user-images.githubusercontent.com/1548285/31039811-dc0ca24c-a54e-11e7-97bb-0de79ecbfe26.jpg)

**Comment by ghost** [comment]
Research done on Regie du Logement returned 25 distinct categories rough drafted from 149 articles of Code Civil du Quebec which may signal that the user story is longer than first anticipated due to not only interactions between the landlord and the tenant but those actors also interacting with the Regie du logement. Clarification with the product owner is necessary as well as subdividing the categories further.

**Comment by arekmano** [comment]
This issue ties in heavily to #8. We will have to complete that in order to get acceptance criteria to function properly.

**Comment by ghost** [comment]
NLP brainstorm
![nlproughdraft](https://user-images.githubusercontent.com/9852083/31089159-1bb8d108-a771-11e7-9911-e89fbad3f3c1.jpg)

**Comment by ghost** [comment]
Questions
![questionspart1](https://user-images.githubusercontent.com/9852083/31089217-45f7df86-a771-11e7-91a7-d199a96164d6.jpg)
![questionspart2](https://user-images.githubusercontent.com/9852083/31089225-4b9c0a8e-a771-11e7-95eb-0b7dd89aeb2e.jpg)

**Comment by ghost** [comment]
![20171004_185909_hdr](https://user-images.githubusercontent.com/9852083/31291007-98023654-aa9c-11e7-845e-717c3b151080.jpg)
