### ISSUE TITLE
Ask only fact questions that are relevant to lease resiliation

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#210]
*Description*
As a user, I would like the system to ask me only questions that are relevant to lease resiliation.

*Scope of Work*
- [x] Evaluate the fact weights for each fact, concerning the lease resiliation outcome
- [x] Limit the set of questions that will be asked to the user to the ones that contain a high absolute weight

*Acceptance Criteria*
- The user is asked only a subset of all possible questions (<10)
- System can still make an accurate prediction with an F1 Score of > 95%

**Comment by Vynny** [comment]
Is there any way to retrieve the map of fact_key:weight?
If so we can can create an ML end point that accepts a claim category type and returns the key value pairs allowing NLP service to build a dict of questions it should ask.

However, if we're going for a more permanent solution, we should implement our intended flow wherein the ML service returns the next fact to be asked, meaning this decision would have to be made on ML side and NLP would require a slight revamp to adhere to the agreed upon flow wherein termination of the conversation is decided by the ML service.

**Comment by arekmano** [comment]
We should go for the quicker solution, rather than the permanent solution IMO, at least for now. Value added is the important metric, not the cleanliness of the solution. 

As for the fact weights, they are static, since we have not retrained the ML since #183. The fact weights are found under that story.

**Comment by Vynny** [comment]
Branch 210/add-fact-ordering adds the ability to specify which facts should be asked for any particular claim category. This functionality can be found in the new factService.py in nlp_controller. 

For the 'lease_termination' category, I have added the most relevant facts, thus reducing the total amount of questions asked to 9. 

Some refactoring was done to ensure that ml service still gets the data that it expects. The downside of this implementation is that it is manual. We still need to specify which facts need to be asked for each claim category. In the future, I think it would be advisable to make this more dynamic, and have some way that nlp service can fetch a relevant fact list for each claim category from ml service, which it can then use to build the list of necessary facts to ask.

**Comment by naregeff** [comment]
We went fro 30+ questions to a handful. Good stuff.
