### ISSUE TITLE
Sign up to Procezeus by asking a tenant/landlord legal question

### ISSUE THREAD

**Issue by lancelafontaine** [Cyberjusticelab/JusticeAI#217]
*Description*
As a user, I would like to submit a question about Quebec tenant/landlord law and get a reply in email form.

*Scope of Work*
- [x] Create a mockup for the landing page
- [x] Create a landing page with a form, to enter an email address and legal question
- [x] Add entries to database when user submits them

*Demo requirement*
1. The user navigates to the landing page
2. User types a question and their email
3. A success modal pops up telling them that we will get back to them

*Acceptance Criteria*
- User enters a question and email
- Email + Question are added to the database

**Documentation, files, diagrams, etc. relating to this feature:**
Url, books, etc.

**Comment by arekmano** [comment]
After this user story and #218 are completed, we should focus on marketing this to the public, to collect data about their questions + email.

**Comment by arekmano** [comment]
This story is very similar to #218. The difference being that for this story, users ask a question. In the other, users simply sign up for the beta

**Comment by arekmano** [comment]
Some drawn mockups about potential solutions: ![Overall Mockup](https://i.imgur.com/vMvzDwT.jpg)

Traditional signup:

![Signup form 1](https://i.imgur.com/TH4QCtj.jpg)

Conversational Signup (I personally prefer this):

![Signup form 2](https://i.imgur.com/3iogwpI.jpg)

One more sign up form (obligatory question): 

![Signup form 3](https://i.imgur.com/7K6X6NZ.jpg)

**Comment by lancelafontaine** [comment]
If we're opting for simplicity, I prefer option 3. Option 2 would showcase our product more but we would have to polish up our existing chat interface.

**Comment by arekmano** [comment]
Since the UI functionality of this feature is minimal (restricted conversation, straightforward answers), we can possibly do 2; it would give our app some personality, which could be good with getting actual beta testers in the future.

**Comment by naregeff** [comment]
functionality works.
