### ISSUE TITLE
Sign up for the Procezeus beta

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#218]
*Description*
As a user, I would like to sign up for the Proceszeus beta with my email address

*Scope of Work*
- [x] Create a mockup for the landing page
- [x] Create a landing page for the application
- [x] Save entered email addresses to the database
- [x] Buy the proceszeus.ca domain and set it up to point to the landing page

*Demo requirement*
1. User navigates to the landing page
2. User enters email address
3. Success modal pops up

*Acceptance Criteria*
- User can enter an email address
- Success modal pops up after entering the address

**Documentation, files, diagrams, etc. relating to this feature:**
Url, books, etc.

**Comment by arekmano** [comment]
Added some mock-ups to #217.

**Comment by naregeff** [comment]
functionality works.
