### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#230]
*Description*
As a stakeholder I would like to know the number of people who look at and sign up for the beta page

*Scope of Work*
- [ ] Add Google Analytics to the Beta sign up page (https://www.google.com/analytics/)

*Demo requirement*
1. The user does visits the beta page
2. Visiting the google analytics page shows an increase is user visits

**Comment by arekmano** [comment]
Google Analytics should be added with our project's gmail account so that everyone has access to the data.

**Comment by dodoels** [comment]
@arekmano gmail credential is available somewhere?

**Comment by arekmano** [comment]
Whoever works on this can use their own google account

**Comment by lancelafontaine** [comment]
An account was created at https://www.google.com/analytics/ with the procezeus@gmail.com email.

**Comment by naregeff** [comment]
saw it work perfectly. cool!
