### ISSUE TITLE
French Sign Up page

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#232]
*Description*
As a user, I would like the system to show me a french beta sign up page after i change the language

*Scope of Work*
- [x] Translate strings to french
- [x] Create option to toggle between french and english

*Demo requirement*
1. The user toggles to french
2. The system shows the french version of the beta sign up

*Acceptance Criteria*
- The user is able to x
- The user sees y
- The user hears z

**Comment by arekmano** [comment]
Current Transcript:

> **zeus**:'Hello there stranger! My name is Zeus and I'm here to assist you with your Québec tenant/landlord issues. I'll be going into beta soon, and would like to get more context about common problems. If you don't mind telling me about any tenant/landlord issues you have, we'll try to get back to you as soon as possible with some useful information.'
> **user**: 'Okay'
> **zeus**:'Would you like to ask me a question about tenant/landlord issue?'
> **user**: 'Sure'  OR 'I have no question'
> **zeus**:'Great! What is your question?'
> **user**: 'Confirm' + QUESTION
> **zeus**:'Mind leaving your email so that we can let you know once our beta is live?'
> **user**: 'Confirm' + EMAIL
> **zeus**:'Would you like to receive updates on our beta test?'
> **user**: 'Sure' OR 'No, thanks'
> **zeus**:'Thank you so much! I'll be in touch. Have a nice day!'
> **user**: 'Close'

**Comment by arekmano** [comment]
Proposed changes to transcript:

> **zeus**: **'Hello there stranger!'**
> **zeus**: **'My name is Zeus and I'm here to assist you with your Canadian tenant/landlord issues.'**
> **zeus**: **'If you don't mind telling me about any tenant/landlord issues you have, I'll try to get back to you as soon as possible with some useful information.'**
> **user**: 'Okay'
> **zeus**: **'Do you have a legal question for me?'**
> **user**: 'Sure'  OR 'I have no question'
> **zeus**:'Great! What is your question?'
> **user**: 'Confirm' + QUESTION
> **zeus**:'Mind leaving your email so that we can let you know once our beta is live?'
> **user**: 'Confirm' + EMAIL
> **zeus**:'Would you like to receive updates on our beta test?'
> **user**: 'Sure' OR 'No, thanks'
> **zeus**:'Thank you so much! I'll be in touch. Have a nice day!'
> **user**: 'Close'

**Comment by arekmano** [comment]
Transcript validation needed

**Comment by dodoels** [comment]
We should have a better list of questions. After #234 is done, the locale file is available in `src/beta_client/src/assets/locale.json`. Everyone can change the text accordingly.

**Comment by naregeff** [comment]
works well. would try to keep bubble sizes consistent if possible.
