### ISSUE TITLE
Polish UI of sign up page.

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#234]
*Description*
As a user, I would like to see a chatbot centered UI

*Scope of Work*
- [ ] Create a high fidelity mock-up
- [ ] Remove intro
- [ ] Remove Landing
- [ ] Chat interface (in full screen)
- [ ] Align text to left

*Demo requirement*
1. The user should be able to access and sign up page and start chatting immediately.
2. The UI should be fully chat centered

*Acceptance Criteria*
1. The user should be able to access and sign up page and start chatting immediately.
2. The UI should be fully chat centered

**Comment by arekmano** [comment]
Added the current transcript + proposed modifications to #232

**Comment by arekmano** [comment]
BUG: After pressing on my response, Zeus appears as thinking before my text appears

**Comment by naregeff** [comment]
Overall great revamp boys.
