### ISSUE TITLE
Adding FAQ Questions from RDL

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#235]
*Description*
As a user, I would like the system to respond to questions listed in the Regie du Logement FAQ

*Scope of Work*
- [x] Scrape all question/answers from https://www.rdl.gouv.qc.ca/en/faqs
- [x] Group common scenarios, and split into different "fact" values. i.e. the following questions:
"If a tenant refuses the rent increase asked by the landlord, can he force the tenant to move?" and "Can a tenant refuse the rent increase asked by the landlord?" can map to facts "refuse_to_move" and "refuse_rent_increase"
- [x] Possibly limit to this user story to the top 10 FAQ questions

*Demo requirement*
1. User asks a question found in the FAQ
2. The system answers with the correct answer

*Acceptance Criteria*
-

**Comment by naregeff** [comment]
works!
