### ISSUE TITLE
DEV STORY: Research and implement production monitoring service

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#237]
*Description*
As a developer, I would like be notified when there are issues with our production systems.

*Scope of Work*
- [ ] Define extent and sophistication of  monitoring and health checks
    - Come up with list of scenarios as "failure states" which should trigger a response from our monitoring solution
- [ ] Research adequate solutions which can address all failure states
- [ ] Implement monitoring solution
- [ ] Ensure that a failure state is able to notify us (through GitHub or Slack)

*Demo requirement*
1. Monitoring system has been able to report a failure state to the team.

*Acceptance Criteria*
- The team is informed when a failure state in production has occurred.

**Comment by lancelafontaine** [comment]
An account was creation at https://uptimerobot.com/ with the procezeus@gmail.com email.

**Comment by lancelafontaine** [comment]
We've integrated the alerting as a channel notification in our Slack group

![image](https://user-images.githubusercontent.com/1548285/34653787-43820fde-f3bf-11e7-8981-fb1d681d37f3.png)

**Comment by naregeff** [comment]
awesome, now we know when things break.
