### ISSUE TITLE
Isolate the Document from a picture and align it

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#25]
*Description*
- As I user, I want to be able to use my lease to obtain facts about my claim

*Scope of Work*

*Acceptance Criteria*

**Comment by arekmano** [comment]
Does this story still apply? Would it be relevant to turn this story into "As I user, I want to be able to use my lease to obtain facts about my claim"? What pieces of information are we extracting from the lease/bill of sale? What is a minimum set of attributes that we can extract?

**Comment by naregeff** [comment]
Yeah, I added two distinct user stories on the Google Sheet and tagged them with "consumer" and "logement".

We can look at this together: I'll bring a lease with me.

Edit: keep in mind, lease form is mandatory.

**Comment by arekmano** [comment]
As part of this story, document segmentation and image transforming was completed.

What remains:
- Actual OCR
- Document Segmentation

**Comment by naregeff** [comment]
Signing off on this part, it works!

**Comment by lancelafontaine** [comment]
![lease_tilted](https://user-images.githubusercontent.com/1548285/36054583-4590bb98-0dc5-11e8-95d9-220ef985100e.png)
![lease_straight](https://user-images.githubusercontent.com/1548285/36054584-45c34dc4-0dc5-11e8-887f-81667f178a2b.png)
