### ISSUE TITLE
Add a question to determine if the beta user is a legal professional.

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#259]
*Description*
As a user, I would like the system to ask me whether I am a legal professional or not.

*Scope of Work*
- [ ] Create UI element that allows the user to input whether or not they are a legal professional
- [ ] Add an API endpoint for recording the user response 

*Acceptance Criteria*
- The user opens up the beta application. User is then shown a dialog that allows them to designate  whether or not they are a legal professional.

**Comment by dodoels** [comment]
This is for beta or main app?

**Comment by arekmano** [comment]
Beta

**Comment by arekmano** [comment]
Beta

**Comment by Vynny** [comment]
Why would we need this for the beta application? Isn't the point to gather questions from users about their problems?

**Comment by naregeff** [comment]
@Vynny , the idea was brought forth in the wake of a proposition for a 4th method for delivering value to end users: to build a knowledge database by using AI to associate questions by people looking for help to answers provided by legal professionals. 

For reference, other 3 methods are (1) scraping FAQs and hard coding answers, (2) using ML on jurisprudence, and (3) using DL on jurisprudence.

I thought it would be in the interest of this 4th method to distinguish between legal professionals and lay people. This would allow us to solicit them if ever we do pursue option 4.

Not a priority, definitely a nice to have.

**Comment by lancelafontaine** [comment]
I'm ready to implement this, but unsure of the conversational element of this. How and when should we ask the user if they are a legal professional?

I'll implement the basics required for this story and some dummy text and the end of the conversation for the moment @naregeff.

**Comment by arekmano** [comment]
Pinging @naregeff for sign off

**Comment by naregeff** [comment]
Functionality demonstrated. 

Whenever possible, 1) update string to "Oh, and one last thing, do you happen to be a legal professional (lawyer, lawyer-to-be, judge, clerk, etc.)?" and 2) align the yes/no buttons to the left.
