### ISSUE TITLE
Parse building rules for claim data

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#26]
*Description*
- As a user, I want to be able to use warranties to obtain facts about my claim

*Scope of Work*

*Acceptance Criteria*

*Story Points*
- ???

*Priority*
- Low

*Risk*
- High

**Comment by arekmano** [comment]
Does this story still apply now that we are orienting ourselves to the problem of Tenant/Landlord Regulation? Is there a way to change this story to something useful, or is it to be cancelled?

**Comment by naregeff** [comment]
Since this refers to a "third party" document, we could replace it by parsing the building rules maybe?

**Comment by arekmano** [comment]
Sure thing. Though, same as #25, we would need a list of relevant facts/information to look for in the document. Also we would need examples to work with

**Comment by arekmano** [comment]
Is there a standard template for building rules @naregeff? Else this may be a very technically complex feature
