### ISSUE TITLE
Migrate to Azure VPS

### ISSUE THREAD

**Issue by lancelafontaine** [Cyberjusticelab/JusticeAI#262]
HTTP response time from static files served by nginx are approaching 1 second, which is extremely poor. Unfortunately, we have no control over the VM provided to us by UdeM.

Migrating our application to a VPS in Azure would allow us to have finer-grained control of our production instance, as well as have nice features like snapshotting.

**Comment by arekmano** [comment]
New instance created, and DNS records updated. Instance: produser@52.226.39.4

**Comment by lancelafontaine** [comment]
Only necessary for sign up site to be migrated for now. CI/CD will still happen at capstone.cyberjustice.ca, which is the VM provided to us by CJL.

**Comment by lancelafontaine** [comment]
Migration to Azure complete for signup page.

https://procezeus.ca/ is front-end (static files served by nginx)
https://procezeus.ca/api/ is back-end (proxied to gunicorn by nginx)
https://procezeus.ca/data/ is password protected and has daily backups of the sqlite db

Front-end responses are now served in ~200ms and back-end responses in ~100ms, which is much more acceptable.

https://capstone.cyberjustice.ca still exists for the main application.
