### ISSUE TITLE
Implement New Beta Workflow

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#272]
*Description*
As a user, I would like the beta interaction to be reworked

I provided a tentative workflow + strings to be used, in Slack.

The main difference is at step 1:

Current workflow asks if user has a question, then provides opportunity to ask question if user answers yes.
Proposed workflow asks user to input question or indicate they have no questions.
Advantage = one less interaction to get to same result.

See workflow on Slack

*Scope of Work*
- [ ] Implement new workflow text

*Acceptance Criteria*
- User opens the beta page.
- Zeus starts conversing using the new conversation text

**Comment by arekmano** [comment]
![image](https://user-images.githubusercontent.com/8740734/34925612-6b26deb6-f978-11e7-8f5e-39e89bef537f.png)

**Comment by naregeff** [comment]
new workflow implemented!
