### ISSUE TITLE
Adding extra FAQ questions from LikeHome

### ISSUE THREAD

**Issue by ghost** [Cyberjusticelab/JusticeAI#280]
*Description*
As a user, I would like the system to see give me quick answers for questions I have regarding leasing and housing.

*Scope of Work*
- [x] Start selecting 10 FAQ questions with their answers and copy paste it into the Google doc
- [x] Start reducing the answer so it fits into a chat format
- [x] Integrate new FAQ LikeHome.info dataset
- 
- [x] Verify that FAQs are getting selected properly and the program gives back the appropriate answer

*Demo requirement*
1. The user asks a question or a variant of LikeHome.info
2. The system ponders and gives back the answer found on LikeHome.info

*Acceptance Criteria*
- The user is able to get the expected answer from the integrated (or variant of) LikeHome.info question

**Documentation, files, diagrams, etc. relating to this feature:**
Url, books, etc.

***Changes***:
- [Optional]

**Comment by ghost** [comment]
@naregeff P.O. needed for priority input

This user story will implement the answers given by LikeHome.info depending on the question submitted by the user.

**Comment by naregeff** [comment]
I think this has potential to add a lot of value for little risk.

**Comment by ghost** [comment]
14 Questions will be delivered in this sprint and more will be delivered in the upcoming sprint.

**Comment by naregeff** [comment]
System able to recognize user questions that are answerable through FAQ and returns answer in bite sized text. Good stuff.
