### ISSUE TITLE
Add a category and entity extraction for rent non-payment

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#291]
*Description*
As a user, I would like the system to be able to tell me how much money I'm entitled to if the tenant doesn't pay rent.

*Scope of Work*
- [x] Create tool to parse and create RASA Data using text parsing to provide entity extraction
- [x] Incorporate flow of questions
- [x] Incorporate data and add entity extraction of money.
- [x] Implement logic with flow of questions that optionally ask questions depending on entity extraction

*Demo requirement*
1. User asks question
2. The system gets categorized as "non-payment"
3. User gives information to system and continues flow of question.
4. System gives back an amount of money corresponding to the issue

**Comment by Vynny** [comment]
Since we're at the point where we're dealing with a lot of NLP data, a tool should be created to automatically generate the rasa json data from a text file, making it a lot easier to edit and maintain in the long term.

I suggest the following format:

#### Format
```
[meta]
() = entity_name1,entity_extractor(optional)
{} = entity_name2,entity_extractor(optional)

[regex_features]
name:regex

[entity_synonyms]
entity:synonym1, synonym2

[common_examples:intent_name1]
sentence1
sentence2

[common_examples:intent_name2]
sentence1
sentence2
```

- **[]** are reserved characters used to identify sections
- **meta** section allows for the definition of meta-characters that define entities
- **regex_features** are simply regex features
- **entity_synonyms** are simply entity synonyms
- **common_examples:intent_name** are common examples for a particular intent


#### Example
```
[meta]
() = money,ner_duckling

[regex_features]
money:$\d(.)?+|\d(.)?+$

[common_examples:true]
my landlord increased my rent by ($500)
i owe my landlord (40 dollars)

[common_examples:false]
i don't owe my landlord any money
i dont have any debts
no
```

**Comment by lancelafontaine** [comment]
Not sure I understand the format of the `meta` section. What is `() = ` for? And will each `meta` line have it's own order for fields? How will we know what type of meta-information this is? 

Otherwise look good to me 👍

**Comment by Vynny** [comment]
The meta section is for defining symbols for a metalanguage that are used to define entities in the common examples.

For example ```() = money,ner_duckling``` means that in the common examples whenever some characters are surrounded with ( ), it defines an entity with name "money" and entity_extractor "ner_duckling".

Let's say I wanted to add a new entity. I could say ```{} = person```. Now you can simply modify the sentence ```my landlord increased my rent by ($500)``` to ```my {landlord} increased my rent by ($500)```.

**Comment by lancelafontaine** [comment]
Thanks, that clears things up. This looks nice 👍 .

**Comment by Samuel-Campbell** [comment]
Command Line Use
------------------------------------------------------
python3 -m util.parse_dataset <read_dir> <write_dir>
example:  python3 -m util.parse_dataset ~/Documents/ ~/Documents/Json/

**DO NOT FORGET THE '/' AT THE END OF YOUR DIRECTORY

**Comment by arekmano** [comment]
3 Points I would like to emphasize:

1. What about the markdown format that is already supported by RASA, found here (https://nlu.rasa.ai/dataformat.html#markdown-format). Is this not sufficient
2. What about using multiple JSON files, (one per intent?) and simply merging them together, using something like https://pypi.python.org/pypi/jsonmerge, or even in a simple "for" loop?
3. What about merging multiple markdown files, using a similar technique to 2.

Simply suggesting KISS alternatives to creating our own file format. I say this because my gut feeling is that we may run into hard to track bugs by rolling our own formatting

**Comment by Vynny** [comment]
Regex features are not supported in the markdown format and they greatly increase confidence. The format is quite simple and easy to use, I converted all the data we currently have without a hitch, including the regex features.

**Comment by naregeff** [comment]
functionality demonstrated, accuracy to be improved in ulterior sprints.
