### ISSUE TITLE
SPIKE: Investigate & present how the RLQ data may be used

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#306]
*Description*
Spike involves research into how we can use the obtained RLQ data

*Scope of Work*
- [x] Research & understand RLQ data
- [ ] Present findings to team
- [ ] PO Meeting to brainstorm user stories

**Comment by arekmano** [comment]
Limitations
==

All data is properly formatted and available to use from July 7, 2013 onward. Cases logged prior to this date contain less attributes.

Available Data
==============

- What the final outcome was of a given case;
    - audience cancelled, case closed, reopened)
    - Decision status (retracted, appealed, mutual agreement)
- All the actions that RDL is aware of given the case:
    - Demand deposits, type of demand, date of deposit, user that deposited the demand, how it was received (mail, in person, etc)
- All possible Demand Request Types:
    - Remboursement, recouvrement de loyer, resiliation, etc (List of possible request types at the bottom)
- Pseudonymized Defendent and Plaintiff of a case
- Address of dwelling related to the case


Possible Benefits to our system
===============================

- Adding all a few additional demand request types to the chatbot
- Improve the demand and outcome extraction steps from our data pipeline using the available demand and outcome types


Registered Request Types
========================

> Annulation de l'acte mettant fin au bail du logement/résidence familiale
> Annulation de la cession du bail du logement servant de résidence familiale
> Annulation de la location de l'immeuble servant de résidence familiale
> Annulation de la sous-location du logement servant de résidence familiale
> Annulation du bail
> Annulation du bail pour cause d'inaptitude du cocontractant
> Annulation du bail pour vice de consentement
> Annulation du contrat
> Annulation du contrat pour vice de consentement
> Annulation du désistement produit par erreur
> Annulation et cassation d'un ordre de comparaître
> Annulation ou réduction d'une clause du bail
> Appel en garantie d'un tiers
> Autorisation d'aliéner un immeuble situé dans un ensemble immobilier
> Autorisation d'effectuer des travaux après l'envoi d'un avis d'intention
> Autorisation d'exécuter l'obligation du locateur
> Autorisation de convertir un immeuble locatif en copropriété divise
> Autorisation de déposer le loyer
> Autorisation de déposer le loyer (inexécution d'une obligation du locateur)
> Autorisation de relouer suite à une reprise du logement
> Autorisation de relouer suite à une éviction
> Autorisation de reprise d'instance
> Autorisation de se désister d'une demande de démolition
> Autorisation pour intervenir
> Autorisation pour évacuation ou dépossession temporaire du locataire
> Autoriser le mineur à intenter seul une action
> Cessation d'une atteinte illicite à un droit/liberté reconnu par la Charte
> Ceux contenus dans la demande portant le numéro ci-haut mentionné
> Contestation d'un avis de non-reconduction du bail donné par le locateur
> Contestation d'un réajustement de loyer
> Contestation d'un réajustement de loyer par le locateur
> Contestation de l'avis de résiliation du bail du locataire d'un L.L.M.
> Contestation de l'inscription dans une catégorie de L.L.M.
> Contestation du refus de réinscription : liste d'admissibilité à un L.L.M.
> Contestation du rétablissement du loyer d'un L.L.M.
> Contestation par un établissement d'enseignement de l'avis de résiliation
> Contestation par un étudiant de l'avis de résiliation du bail
> Demande de rectification d'une décision
> Demande de rétractation d'une décision
> Demande pour décision déclaratoire
> Demande pour décision déclaratoire relative à un ensemble immobilier
> Demande pour décision déclaratoire relative à une copropriété divise
> Demande à la Régie de se prononcer sur l'opportunité de démolir un logement
> Diminution du loyer
> Diminution du loyer suite à des réparations urgentes et nécessaires
> Diminution du loyer suite à une amélioration ou réparation majeure
> Diminution du loyer suite à une expropriation partielle
> Dommages demandés par un locataire suite à la démolition du logement
> Dommages demandés par un locataire suite à la démolition du logement
> Dommages demandés par un locataire suite à la démolition du logement
> Dommages demandés par un locataire suite à la démolition du logement
> Dommages matériels pour atteinte à un droit/liberté reconnu par la Charte
> Dommages moraux pour atteinte à un droit/liberté reconnu par la Charte
> Dommages punitifs pour atteinte à un droit/liberté reconnu par la Charte
> Dommages-intérêts : locataire c. locataire fautif (jouissance normale log.)
> Dommages-intérêts contre l'occupant demandés par le locataire
> Dommages-intérêts contre le locataire demandés par l'occupant
> Dommages-intérêts demandé par le cessionnaire au locataire
> Dommages-intérêts demandés par le locataire suite à une éviction
> Dommages-intérêts entre colocataires
> Dommages-intérêts matériels
> Dommages-intérêts pour troubles et inconvénients
> Dommages-intérêts pour vice de consentement au contrat
> Dommages-intérêts pour vice de consentement au contrat de bail
> Dommages-intérêts punitifs demandés
> Dommages-intérêts punitifs suite au départ définitif du locataire
> Dommages-intérêts punitifs suite à du harcèlement envers le locataire
> Dommages-intérêts punitifs suite à une reprise du logement de mauvaise foi
> Dommages-intérêts punitifs suite à une éviction de mauvaise foi
> Dommages-intérêts suite au départ définitif du locataire
> Dommages-intérêts suite au refus injustifié d'une cession
> Dommages-intérêts suite au refus injustifié d'une sous-location
> Dommages-intérêts suite à la résiliation du bail
> Dommages-intérêts suite à une reprise du logement de mauvaise foi
> Dommages-intérêts suite à une éviction de mauvaise foi
> Déclarer inopposable au créancier un acte juridique
> Déclarer le logement impropre à l'habitation
> Dépôt du loyer
> Dépôt du loyer (inexécution d'une obligation du locateur)
> Déterminer le loyer payable par le locataire
> Déterminer à qui le loyer est payable
> Exception déclinatoire
> Expulsion du locataire après la fin du bail ou après la date convenue
> Exécution en nature contre le locateur demandée par le sous-locataire
> Exécution en nature d'une obligation
> Exécution en nature d'une obligation entre colocataires
> Exécution en nature de l'obligation de l'acquéreur de consentir un bail
> Exécution en nature de l'obligation de l'occupant
> Exécution en nature de l'obligation du locataire demandée par l'occupant
> Évaluation des améliorations ou additions au bien louél
> Fixation annuelle suite à une fixation - bail initial de plus de 12 mois
> Fixation de loyer suite à des travaux de démolition non entrepris
> Fixation de loyer suite à des travaux de démolition non entrepris
> Fixation de loyer suite à des travaux de démolition non entrepris
> Fixation du loyer demandée par le locateur
> Fixation du loyer demandée par un nouveau locataire
> Fixation du loyer demandée par un sous-locataire
> Fixation du loyer et modification du bail demandées par le locateur
> Fixation du loyer suite au rejet d'une demande d'éviction
> Fixation du loyer suite au rejet d'une demande de reprise du logement
> Fixation du loyer suite au rejet d'une demande de résiliation du bail
> Fixation du loyer suite à la non-reprise du logement par le locateur
> Fixation du loyer suite à la renonciation à l'éviction du locataire
> Fixation du loyer suite à une décision reconduisant le bail
> Fixer le loyer exigible sur la base d'un loyer de faveur
> Fixer le loyer exigible sur la base d'un loyer de faveur + modifier le bail
> Homologation d'une transaction
> Indemnité suite à une évacuation ou une dépossession temporaire
> Irrecevabilité de la demande
> Lever la suspension des travaux (améliorations/réparations majeures)
> Mise au rôle par préférence
> Mise en cause d'un tiers
> Modification du bail demandée par le locateur
> Modification du bail du locataire d'un L.L.M.
> Modification du bail suite à une fausse déclaration du locataire d'un L.L.M
> Modification du délai pour entreprendre les travaux de démolition
> Modification du délai pour terminer les travaux de démolition
> Modifier/supprimer une condition abusive (amélioration/réparation majeure)
> Motifs de la demande.
> Opposition au changement d'affectation du logement
> Opposition au changement d'affectation du logement
> Opposition à l'agrandissement du logement
> Opposition à l'agrandissement du logement
> Opposition à la subdivision du logement
> Opposition à la subdivision du logement
> Ordonnance d'accès au logement demandée par le locataire
> Ordonnance d'accès au logement demandée par le locateur
> Ordonnance d'exécution des obligations du locateur (santé et sécurité)
> Ordonnance de cesser des opérations et remettre les lieux en état
> Ordonnance de ne pas entreprendre des opérations contraires à la loi
> Ordonnance de remettre le bien loué dans l'état initial
> Ordonnance de se conformer à une décision sur la conservation des logements
> Ordonnance de suspendre l'exécution provisoire d'une décision
> Ordonnance en exécution provisoire d'une décision de fixation ou révision
> Ordonnance pour défendre l'exécution provisoire d'une décision
> Ordonnance pour fixer un délai pour terminer les travaux
> Ordonnance pour une expertise ou une inspection
> Ordonnance spéciale de comparaître pour outrage au tribunal
> Prolongation du délai pour enregistrer la déclaration de copropriété divise
> Prolonger un délai ou relever des conséquences du défaut de le respecter
> Péremption de l'instance
> Recouvrement d'une somme d'argent due par l'occupant
> Recouvrement du loyer
> Recouvrement du loyer dû
> Recouvrement du loyer entre colocataires
> Recouvrement par l'occupant d'une somme d'argent due par le locataire
> Reddition de compte.  Remise des pièces justifiant les dépenses
> Relance après audition (P) sans frais
> Remboursement : dépenses urgentes et nécessaires encourues
> Remboursement : excédent des dépenses sur indemnité (évacuation temporaire)
> Remboursement des dépenses excédant le loyer retenu
> Remboursement des dépenses raisonnables suite à une sous-location/cession
> Remise au locataire du loyer déposé pour exécuter l'obligation du locateur
> Remise au locateur du loyer déposé
> Reprise du logement
> Reprise du logement
> Requête afin de rejeter une demande jugée abusive ou dilatoire
> Requête pour assigner une personne incarcérée
> Requête pour permission de ratifier
> Requête pour suspension des procédures
> Requête pour une conférence préparatoire
> Requête pour émission d'un mandat d'amener
> Requête pour émission d'une ordonnance spéciale de comparaître
> Restitution d'une somme d'argent payée en trop
> Récusation d'un régisseur
> Réduction de l'obligation pour cause d'inaptitude du cocontractant
> Réduction du loyer par le locataire d'un L.L.M.
> Réduction pour vice de consentement de l'obligation prévue au bail
> Réduction pour vice de consentement de l'obligation prévue au contrat
> Réduction proportionnelle de l'obligation de payer une somme d'argent
> Réinscription au rôle
> Réinscription au rôle
> Réouverture de l'audience
> Résiliation d'un contrat entre colocataires
> Résiliation du bail
> Résiliation du bail (réparations urgentes et nécessaires)
> Résiliation du bail - retard de plus de 3 semaines dans le paiement du loyer
> Résiliation du bail - retards fréquents dans le paiement du loyer
> Résiliation du bail d'un logement impropre à l'habitation
> Résiliation du bail par le locataire suite à une expropriation partielle
> Résiliation du bail par syndicat des copropriétaires-inexécution obligation
> Résiliation du bail par syndicat des copropriétaires-location excédentaire
> Résiliation du bail suite au non-respect d'une ordonnance
> Résiliation du bail suite à l'abandon sans avis du logement impropre
> Résiliation du bail suite à la perte de certification d'une résidence pour aînés
> Résiliation du bail suite à un refus de cession par le locateur
> Résiliation du bail suite à un refus de sous-location par le locateur
> Résiliation du bail suite à une amélioration ou réparation majeure
> Résiliation du bail suite à une fausse déclaration du locataire d'un L.L.M.
> Résiliation du contrat de sous-location par le locateur
> Rétablissement du loyer suite à une décision en diminution du loyer
> Réunion de demandes
> Révision d'une décision du locateur d'attribuer un L.L.M
> Révision d'une décision sur une demande de fixation ou révision du loyer
> Révision de l'inscription dans une catégorie de L.L.M.
> Révision de la décision du greffier spécial autorisant le dépôt de loyer
> Révision de la décision du locateur de reloger le locataire d'un L.L.M.
> Révision de la détermination du loyer d'un L.L.M.
> Révision de la radiation de la liste d'admissibilité à un L.L.M.
> Révision du refus d'inscrire au registre d'un L.L.M.
> Révision du refus d'inscrire sur la liste d'admissibilité à un L.L.M.
> Statuer sur l'opportunité de l'évacuation (amélioration/réparation majeure)
> Statuer sur la durée du bail
> Statuer sur la nature du contrat liant les parties
> Statuer sur la résiliation de plein droit du bail : déguerpissement
> Statuer sur la résiliation de plein droit du bail : logement impropre
> Statuer sur la validité d'un avis
> Statuer sur la validité d'un bail
> Statuer sur la validité d'une cession ou d'une sous-location
> Statuer sur la validité d'une clause prévue au bail
> Statuer sur la validité de l'entente intervenue entre les parties
> Statuer sur le droit à la cession de bail ou à la sous-location
> Statuer sur le droit à la fixation du loyer
> Statuer sur le droit à la résiliation du bail par le locataire
> Statuer sur les conditions d'éviction du logement
> Statuer sur les conditions de reprise du logement
> Statuer sur les motifs de refus de la cession du bail
> Statuer sur les motifs de refus de la sous-location
> Suspension de l'instruction de la demande à la Régie du logement

**Comment by naregeff** [comment]
Thank you for this analysis. Super useful for the meeting on the 27th!
