### ISSUE TITLE
NLP Data Revamp

### ISSUE THREAD

**Issue by ghost** [Cyberjusticelab/JusticeAI#315]
*Description*
As a user, I would like the system to categorize my problem more effectively.

*Scope of Work*
- [x] Cut RLD RLQ in favor of LikeHome when intersecting
- [x] Cut fluff sentences
- [x] Separate FAQ questions and problem categories such that they are relevant only to either landlord or tenant person types

*Acceptance Criteria*
- The user is able to pinpoint their claim category with more accuracy (less errors)
- A landlord is only able to get answers to questions that are relevant to them (FAQ & Claim Category)
- A tenant is only able to get answers to questions that are relevant to them (FAQ & Claim Category)

**Comment by ghost** [comment]
@naregeff Priority level? (basically increasing the intent confidence with which it predicts how to answer- this is way necessary before adding more NLP datapoints)

**Comment by ghost** [comment]
NLP is now revamped to take into account context-sensitive answers depending on the nature (landlord or tenant) of the user using the application.

A tenant will get answers relevant to him while a landlord will get an answer relevant to his situation.

**Comment by ghost** [comment]
Notable ~100-130% increase in intent confidence.

**Comment by naregeff** [comment]
I'm very proud of you, this works great!
