### ISSUE TITLE
DEV STORY: Fix Continuous Deployment

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#345]
*Description*
As a developer, I would like for my changes to be deployed to our prod-like environment after merging to the master branch.

This feature was previously implemented but unexpectedly broke.

*Scope of Work*
- [x] Investigate reason for CD unexpectedly breaking
- [x] Fix CD to work on every merge to master
- [x] Address any remaining issues.

*Acceptance Criteria*
- Production environment is updated.
- Production environment remains functional after update.

**Comment by naregeff** [comment]
It works again 👍

**Comment by naregeff** [comment]
It works again 👍
