### ISSUE TITLE
I want to answer more questions to obtain a more accurate prediction

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#346]
*Description*
As a user I want the system to only ask me the most important questions in order to resolve my case.

*Scope of Work*
- [x] Seperate important from non important questions 
- [x] Establish anti-facts
- [x] Integrate with NLP

*Demo requirement*
1. The user answers a set of important questions for a claim category
2. The user is given a prediction
3. The user is asked whether they would like to continue answering questions to get a better prediction
4. If yes, the user can answer 5 more questions at a time. After 5 questions a new prediction will be given.
5. If more additional facts remain, goto step 3, else end the conversation.

*Acceptance Criteria*
- The user is required to answer a set of important questions
- The user is prompted to answer additional questions once given a prediction

**Comment by naregeff** [comment]
It works! 👍 we proposed an alternate workflow where the user can stop the flow of questions anytime after 5 and request a prediction.
