### ISSUE TITLE
Legal Fees

### ISSUE THREAD

**Issue by Samuel-Campbell** [Cyberjusticelab/JusticeAI#349]
**Description**
As a user, I would like to know how much legal fees I can receive from a particular case.

**Scope of Work**

- [ ] Create supervised learning algorithm benchmark for evaluating predictions
- [ ] Implement supervised learning algorithm that can evaluate whether or not the user is entitled to judicial fees
- [ ] Extract using regex, or similar technique whether or not an individual received judicial fees in a specific case.

**Demo requirement**

- The user selects the facts that are relevant to their case
- The user sends the facts to the system
- The system displays legal fees in integer form. "You are eligible to 80$."

**Acceptance Criteria**
- The user is able perform demo steps
- The F1 score of the supervised learning algorithm is >50%.

Documentation, files, diagrams, etc. relating to this feature:
Url, books, etc.

Changes:
[Optional]

**Comment by naregeff** [comment]
It works! 👍 prediction needs an accompanying text that explains on which basis legal fees are usually awarded.
