### ISSUE TITLE
Additional Indemnity Money

### ISSUE THREAD

**Issue by Samuel-Campbell** [Cyberjusticelab/JusticeAI#350]
**Description**
As a user, I would like to know how much additional indemnity money I can receive from a particular case.

**Scope of Work**
- [ ] Add unit tests for regexes
- [ ] Add anti-facts
- [ ] Create supervised learning algorithm benchmark for evaluating predictions
- [ ] Implement supervised learning algorithm that can evaluate whether or not the user is entitled to additional indemnity money
- [ ] Extract using regex, or similar technique whether or not the individual received additional indemnity money in a specific case.

**Demo requirement**

- The user selects the facts that are relevant to their case
- The user sends the facts to the system
- The system displays legal fees in integer form. "You are eligible to 560$."

**Acceptance Criteria**
- The user is able perform demo steps
- The F1 score of the supervised learning algorithm is >50%.

Documentation, files, diagrams, etc. relating to this feature:
Url, books, etc.

Changes:
[Optional]

**Comment by naregeff** [comment]
It seems that the functionality is well implemented, but will require some review by a legal expert to fine tune predictions. 👍
