### ISSUE TITLE
BUG: Fix Progress Bar Stuck at 100%

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#368]
*Description*
During the time when additional questions are asked, the progress bar was at 100%, but there are still questions to be answered.

**Comment by dodoels** [comment]
What is the bug?

**Comment by arekmano** [comment]
During the demo, for the "additional questions", the progressbar was at 100%, but there were still questions left to answer.

**Comment by Vynny** [comment]
Gotta narrow down whether this is an nlp endpoint issue or a front end issue. I'll test the endpoints again and come back with results.

**Comment by dodoels** [comment]
When user allows more questions, the progress reset 
![image](https://user-images.githubusercontent.com/12192439/37255845-b8fb2daa-2528-11e8-9dc8-2df127d8bfd6.png)

**Comment by Vynny** [comment]
I'm not sure what you mean. The progress doesn't reset, it's recalculated to take into account the additional questions that will be asked.

**Comment by dodoels** [comment]
@Vynny I see, I misunderstood it. But yes, that is the behavior. I think this bug cannot be reproduce.

**Comment by Vynny** [comment]
I haven't been able to reproduce this issue.
