### ISSUE TITLE
Ask when the tenant paid you last

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#369]
*Description*
As a user, I would like the system to ask me when the last time my landlord paid me & take that into consideration for predictions

*Scope of Work*
- [x] Integrate question in the NLP service
- [x] Add new fact on the ML service
- [x] improve the date regex

*Demo requirement*
1. The user is in the nonpayment claim category
2. The system asks how many months the rent is overdue for
3. The user answers
4. The system can correctly classify how many months the user inputted
5. The system can take the number of months into account when giving a prediction

*Acceptance Criteria*
1- Mean squared error lower than previous value
2- R2 value +/- 5% of previous value or greater
3- variance +/- 5% of previous value or greater

**Comment by Vynny** [comment]
This would involve the addition of a date fact type. Duckling can extract dates as a ISO 8601 formatted datetime string. However, date ranges would be significantly harder to extract as they would require a lot more training data to be able to distinguish the start and end entity.

**Comment by arekmano** [comment]
can we present users with a calendar widget for them to select a date?

**Comment by dodoels** [comment]
@arekmano doable, we have the infrastrature for that. Simply returning `'type': 'date'` with the response, and the UI can handle it (either user input the date as string or select from the calendar, or keeping both`

**Comment by Vynny** [comment]
Do we have any facts that expect dates atm? Also are we looking for ranges or single dates?

**Comment by arekmano** [comment]
this would most likely be single dates. i.e. March 12, 2000 - June 15, 2000, since this is the information that would be extracted from the precedents

**Comment by dodoels** [comment]
Why don't we just calculate the range on FE

**Comment by Vynny** [comment]
Has any progress been made on this? Do we have the ability to use date facts with the ML service?

**Comment by Vynny** [comment]
Apparently this was implemented on the ML side as part of #399.

According to @Samuel-Campbell, the "tenant_not_paid_lease_timespan" fact requires a timespan in months representing how long the tenant hasn't paid rent for.

**Comment by naregeff** [comment]
it asks the right questions. 👍
