### ISSUE TITLE
See similar cases

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#371]
*Description*
As a user, I would like the results dashboard to link to similar cases.

*Scope of Work*
- [ ] Either link to SOQUIJ's web site in the user interface, or display the precedent's text.

*Acceptance Criteria*
- The user is able to

**Comment by ghost** [comment]
No way to link SOQUIJ cases to ours as the dossier numbers don't correspond. Hosting the data is impossible due to NDA.

**Comment by dodoels** [comment]
The link to SOQUIJ is randomly generated therefore not able to bind it statically. Due to the NDA we cannot show the precedent data on UI as well. This issue should be closed as won't do.

**Comment by arekmano** [comment]
Apply for SOQUIJ API

**Comment by arekmano** [comment]
I'll attempt a solution this iteration

**Comment by Vynny** [comment]
Perhaps we can give the user's the case number? I believe those are public and they can look it up themselves. SOQUIJ doesnt allow for access via the case number via the URL, you have to go through a search and the result is indexed on their server by what appears to be an md5 id.

**Comment by naregeff** [comment]
win. 💯
