### ISSUE TITLE
BUG: Procezeus doesn't understand issue description

### ISSUE THREAD

**Issue by naregeff** [Cyberjusticelab/JusticeAI#378]
*Description*:
Application currently unusable.

*Replication steps*:
1. Start process as tenant or landlord
2. Input question
3. Attempt to submit
4. Bugs - doesn't accept question
5. Refresh
6. Shows question submitted n times (see screenshot)

<img width="1679" alt="screen shot 2018-03-07 at 2 09 06 pm" src="https://user-images.githubusercontent.com/32269789/37112837-a28fa18c-2211-11e8-979e-0d99897d1e49.png">

**Comment by Vynny** [comment]
This is due to the /weights ML endpoint being broken, resulting in a 500.

**Comment by Vynny** [comment]
![image](https://user-images.githubusercontent.com/1418403/37175008-33f92f60-22e6-11e8-985b-6da1bd62c326.png)

**Comment by dodoels** [comment]
This bug has been fixed in #384
