### ISSUE TITLE
Access system online

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#4]
*Description*
- As a user, I want to access the system on a website using any browser on any device

*Scope of Work*
- Set up domain (2h)
- Set up CI and CD (8h)
- Host the web application (set up HTTP server/proxy) (2h)

*Acceptance Criteria*
- User enters the public URL with a domain. User is shown our system's web application.
- User enters the URL on a mobile device. User is shown the systems web application properly formatted for their device.

*Story Points*
- 8

*Priority*
- Medium

*Risk*
- Low

**Comment by arekmano** [comment]
This story is a natural extension of #2. This would involve obtaining and setting up a domain name for our web application, (with the possible addition of HTTPS support?)

**Comment by naregeff** [comment]
Is it relevant to reference browser support? IMO, it would be an acceptance criteria that the system behave similarly across IE, Chrome, Firefox, Safari, Opera, and other browsers.

**Comment by arekmano** [comment]
Sure it is. Though some of the browsers in that list don't support certain functionality related to PWA. Safari + Edge do not yet support service workers.

**Comment by lancelafontaine** [comment]
- [x] Website currently accessible at https://capstone.cyberjustice.ca
- [x] Continuous deployment is enabled. This means that any changes in our master branch are tested and immediately update our site upon success.
- [x] I tested the site on (Desktop) Chrome, Firefox, Opera and (Mobile) Chrome, Firefox, and the core chat functionality is present. However, given that much of the UI and application functionality will be changing in future iterations, it may make more sense to reevaluate cross-browser support once we're further along into the web application development.

**Comment by naregeff** [comment]
Beautiful, works as advertised.

**Comment by naregeff** [comment]
Beautiful, works as advertised.
