### ISSUE TITLE
Rewrite Chatbot sentences so that they are correctly understood by users

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#400]
*Description*
As a user, I would like the system to communicate with me using sentences that I understand

*Scope of Work*
- [x] Create a list of existing sentences in the application.
- [x] Rewrite sentences found in the chatbot that are not clear
- [x] Rewrite some indemnity questions as compensation instead

*Acceptance Criteria*
- The user is able to communicate with the system in a clear way
- A list of old -> new sentences is attached to this story

**Comment by Vynny** [comment]
Some of these were also addressed in PR #421

**Comment by naregeff** [comment]
Procezeus is a lot more coherent and tactful. 👍
