### ISSUE TITLE
Create a ReadTheDocs Page for Procezeus

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#402]
*Description*
As an open source developer, I would like the system to have clear documentation found in a ReadTheDocs web page.

*Scope of Work*
- [ ] Create a readthedocs page for the system
- [ ] Link READMES to the web page

*Demo requirement*
1. The user does x
2. The system does y
n. Rest of a use case of a flow chart

*Acceptance Criteria*
- The open source developers are able to see our readthedocs page

**Comment by Vynny** [comment]
https://github.com/drdoctr/doctr might be useful here since it can be used to push the docs to gh-pages from our travis builds.

**Comment by mihaiqc** [comment]
Are we still doing ReadTheDocs? Or are we just serving the markdowns as documentation?

**Comment by ghost** [comment]
Read the docs has been deprecated.

Hosting all documentation on: https://cyberjusticelab.github.io/JusticeAI/docs/rendered/
