### ISSUE TITLE
Enter to submit response

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#403]
*Description*
As an user, I would like to press enter to submit my response

*Scope of Work*
- [ ] Link the enter button to form submission on the chatbot

*Demo requirement*
1. The user types in a response and presses enter
2. The response is sent to the server

**Comment by dodoels** [comment]
This is for landing page, not chat interface

**Comment by naregeff** [comment]
great QOL fix. 👍
