### ISSUE TITLE
DEV STORY: Update microservice READMEs

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#405]
*Description*
As an open source developer, I would like the microservices' READMEs to be current.

*Scope of Work*
- [x] Document newly added functionality into the microservice READMEs.
- [x] Create a troubleshoot ReadMe
- [x] Update Web Services ReadMe
- [x] Update NLP ReadMe
- [x] Update ML ReadMe
- [x] Update Backend Readme

**Comment by ghost** [comment]
NLP Doc and Troubleshoot Doc ReadMe updated and merged to master.

**Comment by arekmano** [comment]
Final Version of Docs: https://cyberjusticelab.github.io/JusticeAI/docs/rendered/
