### ISSUE TITLE
Show a "No Regressors" message when there are no regressors to display on the dashboard

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#406]
*Description*
As a user, I would like the system to show me a message when there are no distributions to show for regressors.

*Scope of Work*
- [ ] Create a "NO regressors" message 

*Demo requirement*
1. The user wants to predict lease resiliation.
2. The result dashboard has a "No chart information" message shown.

**Comment by Vynny** [comment]
Personally, I think "No Regressors" is not very user friendly. If there aren't any, simply don't show a chart.

**Comment by naregeff** [comment]
to build on what @Vynny said, we decided to show a blurred graph with string akin to "this functionality is not available for this type of prediction".

**Comment by arekmano** [comment]
Opened new bug to change the text #428. Closing this one
