### ISSUE TITLE
Transpose the similar cases table in the dashboard

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#408]
*Description*
As a user, I would like the similar case dashboard to looks as follow:

| | Your Case | Case 1 | Case 2 | Case 3 |
|-----|------------|--------|---------|-------- |
|Fact 1| True| True | True | True|
|Fact 2| True| True | True | True|
|Fact 3| True| True | True | True|
|Fact 4| True| True | True | True|

*Scope of Work*
- [ ] Transpose the information for the similar cases

**Comment by naregeff** [comment]
straightforward. works great. 👍
