### ISSUE TITLE
Cursor should be change to a pointer for legal definitions

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#409]
*Description*
As a user, I would like the system to change the pointer to a cursor and change color slightly on hover over a legal definition

*Scope of Work*
- [ ] Add CSS so that the required functionality works

*Demo requirement*
1. The user hovers over a highlighted word
2. The color and cursor change.

**Comment by naregeff** [comment]
works wonderfully. 👍
