### ISSUE TITLE
As a user I want the system to predict how much total money I will receive from a case

### ISSUE THREAD

**Issue by Samuel-Campbell** [Cyberjusticelab/JusticeAI#412]
*Description*
The user makes a claim about non payment. The system returns how much total money a user is to receive (claim + indemnity fees).

*Scope of Work*
- [ ] Change tenant_pays_landlord regex
- [ ] Tag precedents
- [ ] Train new model
- [ ] Upload models to CJL

*Demo requirement*
1. The user does x
2. The system does y
n. Rest of a use case of a flow chart

*Acceptance Criteria*
- The user is able to x
- The user sees y
- The user hears z

**Comment by arekmano** [comment]
How does this user story differ from the implemented tenant_pays_landlord classifier + regressor?

**Comment by Samuel-Campbell** [comment]
@arekmano  this is the regressor prediction + indemnity money

**Comment by Vynny** [comment]
Cancelled as this issue arose out of a miscommunication with the stakeholder. After further review, team realized this story isn't necessary.
