### ISSUE TITLE
Dashboard Reporting of Results

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#43]
*Description*
- As a user, I would like claim predictions/results to be displayed in a dashboard report

*Scope of Work*
- [x] Create a high fidelity UI design of result dashboard, with result components
- [x] Create back-end API calls to support dashboard creation
- [x] Implement dashboard UI
- [x] prediction accuracy
- [x] standard deviation + variance of ints
- [x] ml end points

*Acceptance Criteria*
- User completes an interaction with the system. The prediction outcome dashboard is displayed to them.
-- Display questions with most weight for determining answer(s).
-- If answer has value other than boolean, represent answer as range (bell curve).
-- If damages, ventilate into categories whenever possible.
-- If fees are to be awarded, separate legal fees from damages.
-- If red flags in parsed lease, indicate in a separate section.
-- 5 similar decisions -> Include snipets on hover.
-- Field that shows average delay at RLQ for that type of dispute.
-- Icons/links for contacting lawyer, mediation services, etc.

**Comment by naregeff** [comment]
Verified. Priority medium.

**Comment by dodoels** [comment]
@Vynny for this particular issue, I suggest the api returns attributes for different outcome predictions, something like 
```
"response": "Here is my prediction",
"report": true,
"legal_fee": 500,
"lease_termination": true
```

**Comment by Vynny** [comment]
I think there should be a separate domain object for a report. Such that there is a one to many relationship between Conversation and Report. This would allow us to show them a dashboard for every prediction, or at least every prediction for a claim category.

**Comment by dodoels** [comment]
@Vynny how do you handle the transition between the end of the conversation and generating the report?

**Comment by Vynny** [comment]
Well I figure the report can be generated at any time, I need a bit more details about whats expected out of this dashboard to know for sure what to return.

**Comment by dodoels** [comment]
Will create hig-fid mock-up by friday

**Comment by naregeff** [comment]
**Title of each issue identified**

- Display questions with most weight for determining answer(s).
- If answer has value other than boolean, represent answer as range (bell curve).
- If damages, ventilate into categories whenever possible.
- If fees are to be awarded, separate legal fees from damages.
- If red flags in parsed lease, indicate in a separate section.
- 5 similar decisions -> Include snipets on hover.
- Field that shows average delay at RLQ for that type of dispute.
- Icons/links for contacting lawyer, mediation services, etc.

**Comment by arekmano** [comment]
red flags in parsed lease -> impossible, lease parsing cancelled
bell curve -> data manipulation needed to determine what the bell curve data will be
similar decision snippets -> this should be covered by #371 
average delay -> maybe something on the RLQ website?
links -> @naregeff - definitely need a list of what to include

**Comment by dodoels** [comment]
![image](https://user-images.githubusercontent.com/12192439/37244171-f3b369b6-2452-11e8-93c4-c54b514279e0.png)
![image](https://user-images.githubusercontent.com/12192439/37244172-f5fac944-2452-11e8-8147-051685c3ce0b.png)

in sum:

UI 
- expand the sidebar for dashboard
- remove upload features (both UI and backend, since no more OCR)
- show all data as shown in the mockup

ML: 
- side returns some new data to existing predict endpoint: 
1) accuracy %, 
2) data needs for the bell curves for all numerical prediction, 
3) a list of outcome prediction (only the true values) 
4) 5 similar precedent with facts 
5) number of precedents we used to train the models (optional)
6) number of similar precedent to user's case (optional)

NLP: 
- new object for saving the new data, along with a new endpoint to return these data

BE: 
- new endpoint to fetch the above data from NLP

**Comment by dodoels** [comment]
@Vynny 
```
report: {
    accuracy: 90,
    data_set: 350000,
    similar_case: 50,
    curves: {
        legal_fees: ['whatever data is needed to create a bell curve'],
        additional_indemnity_fees: ['whatever data is needed to create a bell curve']
    },
    outcomes: {
        lease_termination: 1,
        order_resiliation: 1,
        apartment_impropre: 1,
        legal_fees: 82,
        additional_indemnity_fees: 1000
    },
    similar_precedents: [
        {
            precedent: 'AZ-1111111',
            facts: {
                f1: 1,
                f2: 1,
                f3: 1,
                f4: 1,
                f5: 1
            },
            outcomes: {
                o1: 1,
                o2: 1,
                o3: 1
            }
        },
        {
            precedent: 'AZ-222222',
            facts: {
                f1: 0,
                f2: 0,
                f3: 0,
                f4: 0,
                f5: 1
            },
            outcomes: {
                o1: 0,
                o2: 0,
                o3: 1
            }
        }
    ]
}
```

**Comment by naregeff** [comment]
looks lit 🔥.
