### ISSUE TITLE
Show Conversation Progress %

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#44]
*Description*
- As a user, I would like to see the progress of the conversation until an outcome is displayed

*Scope of Work*
- [x] Create high-fidelity mock-up of progress module
- [x] Implement progress visual component
- [x] Calculate number of interactions required (either average or specific to the current interaction) on the back-end
 
*Acceptance Criteria*
- When user starts an interaction with the system, the progress is at 0%.
- As the user interacts with the system, the progress continually increases.
- At the result display screen, the progress bar shows as 100%

**Comment by naregeff** [comment]
Scope of work hasn't been defined yet, but seems relatively simple. 
Low priority (but should be done).

**Comment by arekmano** [comment]
Odd, i remember writing the description for this one. GitHub bug.

**Comment by dodoels** [comment]
@Vynny can you return the remainning number of question or percentage to conversation end point?

**Comment by Vynny** [comment]
Yes but full implementation will have to wait for #346 to be complete since it is revamping how facts are determined for a claim. I could however add a dummy return to the API so that you can start working on it.

**Comment by Samuel-Campbell** [comment]
#346 is almost complete @choitwao

**Comment by Vynny** [comment]
I'm taking ideas on how to implement this.
We have important facts and non important facts. 
All important facts must be asked before the first prediction is given.
Once the first prediction is given, the user is asked whether they want to answer more questions. If they accept, 5 (max) non important facts are asked before another prediction is given.
If another prediction is given and non important facts remain, the user will be prompted another time as to whether or not they want to continue.

A) The progress can be set to 100% once the important facts are asked. If they wish to answer more questions, the progress will be set such that once they answer the next batch of questions it will be set to 100% again. 

B) Simple questions-answered/total-questions ratio.

**Comment by Vynny** [comment]
Went with option A, more details can be seen at PR #354.

**Comment by naregeff** [comment]
Works like a charm 👍
