### ISSUE TITLE
Accept user feedback within system

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#45]
*Description*
- As a user, I would like to give feedback on missing features, so that they can later be implemented

*Scope of Work*
- Design Feedback component's UI
- Implement Feedback component
- Write Unit tests demonstrating feedback functionality
 
*Acceptance Criteria*
- User presses a button, types a string and presses submit. The user gets a confirmation popup saying that his feedback is received.
- User feedback strings, their conversation identifiers and question identifier are persisted within the database.

*Story Points*
- 3

*Priority*
- Medium

*Risk*
- Low

**Comment by arekmano** [comment]
clarification is needed: Should the feedback be obtained via an email address (user sends via their Gmail or Outlook client), or should we handle the feedback that is given within our system, i.e. create a feedback form?

**Comment by naregeff** [comment]
Verified.
Priority medium (super important for improving through iterating, but it isn't a core feature).
Feedback handled within the system. UI link, popup form, possibility to include screenshots maybe (encourage / allow user to be as precise as possible).

**Comment by arekmano** [comment]
This story will be needed if we are to have beta testers

**Comment by arekmano** [comment]
Something similar to this should be good:
![](https://i.giphy.com/media/xTiTnlktZPH07oxhYs/giphy.webp)

In short: Give USERS GIFS AND THEY WILL RESPOND!

**Comment by lancelafontaine** [comment]
This is for users to send us feedback in the form of free form text.

**Comment by Samuel-Campbell** [comment]
User feedback strings, their conversation identifiers and question identifier are persisted within the database.

I don't understand this. Why not just leave it anonymous

**Comment by naregeff** [comment]
works! we'll make it look sexier and add gifs.
