### ISSUE TITLE
Indicate the understood response from the user's answer

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#46]
*Description*
- As a user, I would like to validate and correct the facts and categories that the system understood

*Scope of Work*
- [x] For 3 sample classifications that the system makes, through NLP, the system must output what it internally understood. (i.e. for NLP, the system would signal the user the classification that it was able to extract from the user input).
- [ ] Create a high-fidelity mock-up of interaction.

*Acceptance Criteria*
- System asks a fact question.
- User enters a textual answer to the system. The response of the system contains a list of labels that it was able to extract from the textual answer, indicating which one the system thinks is the most likely.

*Story Points*
- 8

*Priority*
- High

*Risk*
- Low

**Comment by naregeff** [comment]
Verified, high priority. This will allow training of the AI system, right?

**Comment by arekmano** [comment]
Yes. Also it will allow us to make correct predictions, rather than having incorrect facts about the case. Depending on the UI design, this story and #65 potentially overlap.

**Comment by arekmano** [comment]
Moved to iteration 5, as the UI components have not been worked on.

**Comment by naregeff** [comment]
no high-fi mockup. it's been developed and functional, but UI needs work. can sign off, conditional to adding this to a new "_UI review" story_".
