### ISSUE TITLE
Interactive JusticeAI avatar

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#47]
*Description*
- As a user, I would like the JusticeAI avatar to change, depending on the conversation context

*Scope of Work*
- Searching for emotional avatar open source vs designing one ourselves (?)
- Implement avatar within the chat interface
- Develop switching mechanism to be responsive depending on the development of the conversation
(Asking for name + who they are phase -> Classification of problem phase -> questioning phase -> Conclusive phase, 1 avatar each)

*Acceptance Criteria*
- The avatar is changing as the conversation is progressing depending on the different phases described above

*Story Points*
- 8

*Priority*
- Low

*Risk*
- Low

**Comment by naregeff** [comment]
Verified, low priority.

**Comment by arekmano** [comment]
Evaluate list of emotions that zeus should have.
