### ISSUE TITLE
List Uploaded Documents

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#48]
*Description*
- As a user, I would like to see a list of documents that I've uploaded to the system

*Scope of Work*
- Create a UI Mockup for the list of documents view
- Create a component which will show the list of documents associated with the conversation

*Acceptance Criteria*
- The user uploads a document; The user can now see the document icon and file name in in the document list view.

*Story Points*
- 5

*Priority*
- Medium

*Risk*
- Low

**Comment by arekmano** [comment]
![img_20171009_170210](https://user-images.githubusercontent.com/8740734/31531261-fad17f80-afb3-11e7-8191-c23819cdf9cc.jpg)

Sketch was drawn during first design meeting.

Essentially, there would be a second view, where a list of all files would be shown.

**Comment by naregeff** [comment]
Verified. Will decide how to implement the frontend part with @choitwao when we talk UI.

**Comment by arekmano** [comment]
Priority?

**Comment by choitwao** [comment]
@arekmano @arekmano  
If users can download/view the uploaded files from the sidebar/menu/list, do we still need issue #49 (download/view uploaded files by clicking in the chat)?

**Comment by dodoels** [comment]
@arekmano @naregeff 

If users can download/view the uploaded files from the sidebar/menu/list, do we still need issue #49 (download/view uploaded files by clicking in the chat)?

**Comment by arekmano** [comment]
This story involves the only the list view for uploaded documents. #49 involves being able to download+view previously uploaded documents

**Comment by naregeff** [comment]
Seems ok, verified, low priority.

**Comment by naregeff** [comment]
Seems ok, verified, medium priority.

**Comment by arekmano** [comment]
Cancelled as files will no longer be retained within our system. They will be parsed and then discarded right away.
