### ISSUE TITLE
Open Uploaded Files

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#49]
*Description*
- As a user, I want to be able to open files that I've uploaded to the system

*Scope of Work*
- [ ] Implement download or view document functionality within the application

*Story Points*
- 3

*Priority*
- Medium

*Risk*
- Low

*Demo requirement*
1. The user has conversation with the system and the systems ask the users to upload a file
2. After the file has been uploaded, the user can see the file on the page
3. The user then clicks on the file icon and the file should open in the same page. 

*Acceptance Criteria*
- When the user clicks on a file icon, the file opens on the same page.

**Documentation, files, diagrams, etc. relating to this feature:**
Url, books, etc.

***Changes***:
- [Optional]

**Comment by naregeff** [comment]
Verified, medium priority.

**Comment by arekmano** [comment]
Cancelled as files will no longer be retained within our system. They will be parsed and then discarded right away.
