### ISSUE TITLE
Uploading files to the system

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#50]
*Description*
 As a user, I want to be able to upload a file to the system

*Scope of Work*
- [ ] User can upload document using the mobile phone camera
- [ ] User can upload document using drag and drop

*Story Points*
- 5

*Priority*
- Medium

*Risk*
- Low

*Demo requirement*
1. The user is in a conversation with the chatbot
2. The system interprets the need to upload evidence for the user
3. The system shows a file upload interaction container/button for the user to upload the file
4. The user can drag or click "Upload" on the container where he will select the file and confirm using the file explorer of his operating system.
5. The file is written to the servers and attributed to the user's ID.

*Acceptance Criteria*
- The user is able to see the prompt accordingly to the message
- A container pops up that the user can select to choose the file to upload
- The file is written on the servers attributed to the user's ID

**Documentation, files, diagrams, etc. relating to this feature:**
Url, books, etc.

***Changes***:
- [Optional]

**Comment by naregeff** [comment]
Approved, medium priority.
