### ISSUE TITLE
Extract facts from precedents (NLP)

### ISSUE THREAD

**Issue by lancelafontaine** [Cyberjusticelab/JusticeAI#67]
*Description*
- As a user that's facing eviction, I'd like to see which precedents relate to eviction

*Scope of Work*
- Find a corpus in French that makes sense from NLP on data that can help train fact extraction
- Be able to determine if the case relates to lease termination (eviction)

*Acceptance Criteria*
- Show one randomly selected precedent containing eviction (80% F1 measure)

*Story Points*
- 40

*Priority*
- 

*Risk*
-  High

**Comment by arekmano** [comment]
Closed as a better defined user story was created #74
