### ISSUE TITLE
User Interaction Design

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#69]
***Description***

- As a user, I want to have a complete end-to-end user experience of the system
- We need to create a low-fidelity mock-up to show the whole system flow that includes all desire features we have created stories for.

***Scope of Work***

Create low-fid mock-up met the following requirements:

1. Chat Interface
- The conversation between bot and the end user must be interactive and not as a simple chat window.
- Must show EULA at the beginning of the conversation as part of the conversation. The EULA may include a hyperlink that directs to complete EULA and shows only the essential outline of it.
- BOT should be able to prompt upload option inside the chat bubble. This option should include 1) upload button that user can select local files, 2) drag and drop local files, 3)  a camera button to open camera
- BOT should give pre-selected answers set and show them as buttons. These buttons should be inside the chat bubble or above text input. The option "an input is missing" should be given if the pre-selected answers don't include user's desired option. 
- BOT should regularly show a recap to make sure the user's previous inputs are desired. This is more on functionality side but we should show this flow in mock-up as well. Following the recap, there should be a way the users can re-enter their answers if they want to.
- BOT should be able to generate a report. The report should 1) show graph and diagram, 2) show proper data, 3) show download/email transcript, demand letter generation, 4) should follow with lawyer contact, email, website
- User text input, along with voice input button
- Should show legal definition as a tooltip.

2. Side Bar Interface
- Should show user basic profile
- Should show account options (login, logout)
- Should show a list of existing conversation (case) and previous ones
- When toggling down the case, there should be 1) a progress bar (i.e. how far is the user to final report), 2) a list of uploaded files 

3. Landing Page 
- Should have a button to start the process

*Acceptance Criteria*
- Create low-fid to show all the features listed above in scope of work

***Story Points***
- 13

***Priority***
- Medium

***Risk***
- Low

**Comment by arekmano** [comment]
This story does not represent a benefit to the user. We need to discuss before it is included in an iteration

**Comment by dodoels** [comment]
Closed the story since it does not represent a benefit to the user.
