### ISSUE TITLE
Interface Branding Design 

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#71]
*Description*
- As a user, I want to see an interactive, interesting and appealing branded interface

*Scope of Work*
- [ ] Implement UI Logo
- [ ] Implement UI avatar
- [ ] Implement UI colour scheme
- [ ] Report to Product Owner ( @naregeff ) for approval
- [ ] Create high-fid mock-up based on approved UI
- [ ] Implement the UI to existing functional components as a whole (ensure messages are properly displayed and transmitted accordingly)

*Demo requirement*
1. The user visits the website
2. The user inputs his name
3. The system returns back according reply
4. The user inputs their status
5. The user returns back according reply
6. The user inputs their problem
[See Github Issue #20 for more information towards the interaction]

*Acceptance Criteria*
- The user sees a web application that should be implemented with the wishes and the preferences of the product owner
- The user is able to interact with the bot using the chat interface to the capability of its present development

*Story Points*
- 8

*Priority*
- Medium

*Risk*
- Low

**Documentation, files, diagrams, etc. relating to this feature:**

***Changes***:
- [Optional]

**Comment by arekmano** [comment]
We do not decide the priority of stories.

**Comment by naregeff** [comment]
Verified, medium priority.
