### ISSUE TITLE
Precedents: Eviction

### ISSUE THREAD

**Issue by ghost** [Cyberjusticelab/JusticeAI#74]
*Description*
As a user, I would like the system be able to give me back cases relating to evictions

*Scope of Work*
- [ ] Be able to parse through 1 textfile
- [ ] Be able to read one text file and detect back if the case is related to eviction or not accompanied by the name of the text file and it's "No demande"
- [ ] Be able to do it to a user-set amount of files in one command

*Story Points*
- 8

*Priority*
- High

*Risk*
- High

*Demo requirement*
1. The user sets a specific amount of files he wants to inspect (which are randomly selected by the user)
2. The system regurgitates back every file randomly selected with: whether or not they are pertaining to eviction, their "no demande" and their text file
3. Manually verify said text files to confirm it properly detected whether or the case has to do with eviction

*Acceptance Criteria*
- The user is able to select a set amount of randomly selected cases to go through
- System provides back the set amount with an according list of their text file names and whether or not they pertain to eviction

**Documentation, files, diagrams, etc. relating to this feature:**
Url, books, etc.

***Changes***:
- [Optional]

**Comment by naregeff** [comment]
I'm not sure where this user story comes from or what exactly it is meant to do. Please explain. Unverified for the time being.

**Comment by arekmano** [comment]
There are a few ways that precedent data may be used by our system to make predictions about a current user's claim. One of the ways that this can be done involves a "feature extraction" step, where the information found within precedents (human-readable) is extracted into vectors (machine-readable). This story involves the research and creation of feature extraction for a one of these features that will have to be extracted (was the tenant evicted or not). 

This approach will later be generalized to accommodate different feature types.

**Comment by naregeff** [comment]
Yeah, this one is good. Verified.

**Comment by arekmano** [comment]
Cancelled as the project goals have pivoted #105
