### ISSUE TITLE
Better Classification for Tenant/Landlord Problem

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#75]
*Description*
As a user, I would like the problem classification to have a higher precision and recall, so that I can properly classify my response

*Scope of Work*
- [x] Re-implement nlp service system using RASA
- [x] Research improvements to classifying text in NLP
- [x] Augment current data on classification of Tenant/Landlord's problem for "Deposit" category
- [x] Augment current data on classification of Tenant/Landlord's problem for "Rent Change" category
- [x] Augment current data on classification of Tenant/Landlord's problem for "Lease Termination" category
- [x] Augment current data on classification of Tenant/Landlord's problem for "Non Payment" category
- [x] Implement classification improvement

*Story Points*
- 8

*Priority*
- Medium

*Risk*
- Medium

*Acceptance Criteria*
- System classifies the Tenant/landlord's problem with an F1 score of 85% or higher

**Comment by naregeff** [comment]
Verified. Realistically, I believe this one will be at a medium priority, as we need the system to improve its classification. Keep in mind that depending on what accuracy threshold we're able achieve with the initial story, this may change to become a high (or low) priority item.

**Comment by arekmano** [comment]
Updated

**Comment by arekmano** [comment]
Just checked out RASA NLU library, which is a wrapper around a suite of NLP tools. This may come in handy for NLP as it will have a better performance than a single technique

**Comment by Vynny** [comment]
New persistence model structure 
![20171103_182230_1024](https://user-images.githubusercontent.com/1418403/32455314-e2d45822-c2ef-11e7-9d6e-06c5b6703c43.jpg)

**Comment by Vynny** [comment]
System communication flowchart, to be followed when implementing new NLP system.

![20171103_182253](https://user-images.githubusercontent.com/1418403/32455358-090c0ae4-c2f0-11e7-8197-7d2f3aec3aaf.jpg)

**Comment by Vynny** [comment]
Proposed ER diagram. I was thinking that the Fact table could represent the existence of a particular fact in the system, meaning if we had 20 total facts that could be resolved, there'd be 20 columns.
FactEntity would have a foreign key to the Fact, and would signify a resolved fact with a determined value. 

![erdiagram](https://user-images.githubusercontent.com/1418403/32587712-f2eccc5a-c4d7-11e7-8658-a12ebbd717e9.PNG)

**Comment by lancelafontaine** [comment]
Looks good to me, but every fact would be stored as a row (not as a column like you mentioned), right?

**Comment by Vynny** [comment]
Oh yeah my bad, typo. Every Fact would be a row. Every FactEntity would simply hold a value and a reference to the Fact that the value is for. That way if you want to refer to the existence of a fact, you'd make a relation with the Fact table, however if you wanted a relation with resolved facts, you'd have a relation with FactEntity.

An example flow would be, 
1) ML tells NLP that the next fact that needs to be resolved is Fact a
2) current_fact relation in conversation is set to point to Fact a in the Fact table.
3) The user answers a question pertaining to Fact a 
4) New Message with the response text that references Fact a (relevant_fact relationship) is created
5) NLP resolves the fact as for example "false", knowing the relevant type by looking at Fact.type
6) NLP passes the Fact id and the resolved value to ML which creates a FactEntity that has value "false" and points to Fact a. 
7) ML returns next Fact to ask question for

**Comment by lancelafontaine** [comment]
Yup, that's exactly how I had imagined it to be. Makes sense to me, I can't spot any obvious flaws. :+1:

**Comment by arekmano** [comment]
Closing as we had previously obtained verbal signoff
