### ISSUE TITLE
Evaluate ML requirements

### ISSUE THREAD

**Issue by arekmano** [Cyberjusticelab/JusticeAI#88]
*Description*
As a CJL administrator, I would like to know the computing resources required for Machine learning 
(Research-oriented task)

*Scope of Work*
- [ ] Evaluate unsupervised learning algorithms (Gaussian Mixture, K-Means training/prediction times for 300*45000 (estimated facts) inputs into 250 clusters (estimated fact types)
- [ ] Evaluate unsupervised learning algorithms training times for clustering 250*45000 (estimated facts) inputs into 100 clusters (estimated case types)
- [ ] Evaluate supervised learning algorithm training times for 250*45000 for training/predicting output vectors

*Story Points*
- 8

*Priority*
- High

*Risk*
- Medium

*Acceptance Criteria*
- Have computing resource requirements to submit to the Lab

**Comment by arekmano** [comment]
Laptop specs:
Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
8 GB RAM

Testing conducted using Sklearn python library, using CBOW vectorization of facts.

Unsupervised GMM clustering algorithm training time for 1000 precedents: 
~ 8 minutes (with 1GB peak RAM utilization)

Unsupervised GMM clustering algorithm training time for 10000 precedents: 
~ 66 minutes (with 2GB peak RAM utilization)

Unsupervised GMM clustering algorithm training time for 40000 precedents: 
~ 220 minutes (with 6GB peak RAM utilization)

**Comment by arekmano** [comment]
Testing conducted using Keras & Tensorflow, using a FC network with 1 hidden layer. Reuters training set was used.

Training time for 1000 sequences:
~ 35 seconds (4 GB peak RAM utilization)

Training time for 10000 sequences:
~  4 minutes (consistent 100% 8 GB utilization)

Training time for 100 000 sequences (estimated number of facts):
~  30 minutes (consistent 100% 8 GB utilization)

**Comment by arekmano** [comment]
Recommended specifications for Machine Learning computing resources for the project:

16 GB of RAM
3.5 GHz Multicore CPU (4+)
50 GB of HD space

The equivalent for Azure and AWS are listed below (any one of these will satisfy our needs):

# Microsoft Azure:
## General compute
- B4MS
- A8v2
- D3
- D3v2

## Compute Specific
- F8
- F8v2


Additional EBS storage is required (~5$)

Reference URL:
https://azure.microsoft.com/en-ca/pricing/details/virtual-machines/linux/


# Amazon
- t2.xlarge
- c4.2xlarge

Additional EBS storage is required (~5$)

Reference URL:
https://aws.amazon.com/ec2/instance-types/

Pricing URL:
https://aws.amazon.com/ec2/pricing/on-demand/
https://aws.amazon.com/ebs/pricing/

**Comment by naregeff** [comment]
Good stuff. 

1) what would be the time usage requirements? Azure calculates usage by the hour IIRC
2) no GPU intensive ML tasks finally? 
3) are these preliminary needs subject to change or is it a final evaluation of needs?
4) is this sufficient for ALL the types of ML algorithms you wish to try?

we should be able to clear some of these up this evening.

**Comment by naregeff** [comment]
Looks good to me. Relaying info.
